### ISSUE TITLE
USER STORY: Delete Products from the Store

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#14]
As a **Site Admin** I want to **be able to remove products from the store** so that **the inventory is relevant and any outdated or discontinued items are eliminated**

### Acceptance Criteria
- [x] Admin can access a dedicated dashboard to remove products from the store
- [x] The process for removing products is straightforward and easy to navigate
- [x] The system provides a confirmation step to prevent accidental removal of products
- [x] The product is immediately removed from the store’s inventory and is no longer visible to customers on the store’s website

### Tasks
- [x] Create an admin interface that allows to remove products from the store
- [x] Design and implement deletion process that is easy for admins to use
- [x] Implement a confirmation step to ensure that products are not removed accidentally
- [x] Ensure that removed products are instantly removed from the store’s inventory and are no longer visible on the store’s website
