### ISSUE TITLE
USER STORY: Design Database Schema

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#2]
As a **Developer** I want to **design a database schema** so that **I can efficiently store and manage platform content, ensuring optimal performance, scalability, and flexibility**

### Acceptance Criteria
- [x] The database schema containing all neccessary tables
- [x] Users should be able to search and retrieve records based on categories

### Tasks
- [x] Design tables
- [x] Establish relationships between the tables to ensure data integrity and efficient querying for platform content
