### ISSUE TITLE
USER STORY: Add a Review

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#25]
As a **Registered Customer** I want to **be able to comment on products** so that **I can provide feedback**

### Acceptance Criteria
- [x] All feedbacks are visible on the platform
- [x] Registered users fill in the required fields and submit the form, then the form performs data validation to ensure required fields are filled and data is correctly formatted
- [x] If there are any validation or submission issues, clear error messages are displayed
- [x] Reviews are displayed below the product info on single product page, along with username and timestamp

### Tasks
- [x] Implement a review form below each product, accessible to registered users who already purchased the item
- [x] Set up a template for rendering the review form, ensuring a user-friendly interface for authors
- [x] Implement clear error messaging and feedback mechanisms to notify authors of any issues that may arise during review submission, such as invalid input or submission errors
- [x] Add notifications to confirm successful review submission, providing a sense of accomplishment and confirmation that their review has been saved
