### ISSUE TITLE
USER STORY: Performance Optimization

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#31]
As a **Developer** I want to **improve the platform load speed and response to user interactions** so that **users can have a seamless experience**

### Acceptance Criteria
- [x] Backend and frontend optimizations are implemented to minimize server response time and client-side processing overhead
- [x] Media assets, such as images and videos, are optimized for web delivery to reduce file sizes and loading times
- [x] Performance metrics meet or exceed industry standards

### Tasks
- [x] Do a performance audit to identify areas for improvement in the platform's performance
- [x] Optimize images and multimedia content for web delivery by compressing and resizing them appropriately
- [x] Implement performance optimisation based on monitoring data and load testing results
