### ISSUE TITLE
USER STORY: Facebook Marketing

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#33]
As a **Developer** I want to **be able to share the business on Facebook** so that **I can reach and market to a larger audience**

### Acceptance Criteria
- [x] A Facebook page mockup for the business is successfully created
- [x] The Facebook page contains posts that advertise the site and its offerings

### Tasks
- [x] Set up a Facebook page mockup for the business, ensuring it includes relevant information, branding, and contact details
- [x] Plan and create posts that effectively advertise the site, including promotions, updates, and engaging content
- [x] Attach screenshots of the mockup page to README.md
