### ISSUE TITLE
USER STORY: User Story Testing

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#39]
As a **Developer** I want to **ensure that user stories are thoroughly tested** so that **the acceptance criteria are met and the application delivers the expected functionality**

### Acceptance Criteria
- [x] Document test results including the issues/bugs identified
- [x] Ensure that all test cases are completed before considering the user story as complete

### Tasks
- [x] Based on the acceptance criteria, create test scenarios that cover all possible use cases
- [x] Execute each test case, following the steps outlined and recording the results
- [x] Keep test documentation up to date with any changes in requirements or test scenarios
