### ISSUE TITLE
USER STORY: Password Reset

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/winery#9]
As a **Registered User** I want to **be able to recover my password in case I forgot it** so that **I can recover access to my account**

### Acceptance Criteria
- [ ] Users can access a password reset form
- [ ] Users can reset their password using the provided instructions

### Tasks
- [ ] Create a password reset form with input fields
- [ ] Allow users to reset their password using the provided instructions
- [ ] Test functionality with valid credentials
- [ ] Test functionality with invalid credentials
